favorite_foods = ['pizza', 'burger', 'gyros', 'crepe', 'cake', 'pancakes', 'steak']
print(favorite_foods)
favorite_foods.append('coffeecino')
print(favorite_foods)
favorite_foods.insert(3, 'squid')
print(favorite_foods)
del favorite_foods[3]
print(favorite_foods)
not_favorite_foods = favorite_foods.pop(5)
print(favorite_foods)
print(not_favorite_foods)
favorite_foods.remove('coffeecino')
print(favorite_foods)
too_casual = 'steak'
favorite_foods.remove(too_casual)
print(favorite_foods)
print(f"\n{too_casual.title()} is too casual for me.\n")
print(favorite_foods)
print(sorted(favorite_foods))
print(sorted(favorite_foods, reverse=True))
print(favorite_foods)
favorite_foods.reverse()
print(favorite_foods)
favorite_foods.reverse()
print(favorite_foods)
favorite_foods.sort()
print(favorite_foods)
favorite_foods.sort(reverse=True)
print(favorite_foods)
print(len(favorite_foods))
